<?php

class APHeaderController extends MPComponent {

    public function __GET($params)
    {
        $this->template = "APHeader.twig";

        $this->pages = $this->_AdminPanel->getPages();

        $this->navDisabled = false;

        $this->userRestricted = false;

        $this->__render();
    }

    public function __POST($params)
    {
        parent::__POST($params); // TODO: Change the autogenerated stub
    }
}